apiVersion: v1
kind: Service
metadata:
  name: tasklist-service
spec:
  selector:
    app: tasklist
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasklist
spec:
  selector:
    matchLabels:
      app: tasklist
  replicas: 4
  template:
    metadata:
      labels:
        app: tasklist
    spec:
      containers:
      - name: tasklist
        image: tasklist:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
