apiVersion: v1
kind: Service
metadata:
  name: tasklistwsb-svc
spec:
  selector:
    app: web-yolo
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-yolo
spec:
  selector:
    matchLabels:
      app: tasklistwsb
  replicas: 1
  template:
    metadata:
      labels:
        app: tasklistwsb
    spec:
      containers:
      - name: tasklistwsb
        image: tasklistwsbregistry001.azurecr.io/takslistwsb:v1
        ports:
        - containerPort: 80

